import { ThirdwebProvider,ChainId } from "@thirdweb-dev/react"
import network from "@/utils/network"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode

}) {
  return (
    <ThirdwebProvider activeChain={network}>
    <html lang="en">
      <body>{children}</body>
    </html>
    </ThirdwebProvider>
  )
}
